### ISSUE TITLE
Switch Wally to use Gold Realm

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1001]
In order to migrate to Keycloak gold, WALLY has to be updated to no longer use the deprecated gatekeeper client.  Our authentication has to be done on our own backend and we should be requesting tokens from the SSO team's api not a custom proxy that we spun up.  So in acceptance criteria are steps to track what has been done to make that happen on the current PR.

**Purpose**
The Keycloak ID isn't available in Gold, which is why we need to switch to using the GUID (which *is* available in Gold).

**Acceptance Criteria:**
- [x]  WALLY logic for configuring gatekeeper is removed (frontend/AuthService.js)
- [x]  AuthService.js is configured to connect to the SSO api instead of gatekeeper
- [x]  main.js initializes the new Keycloak client to check authentication
- [x]  The frontend now correctly handles the new token to display username in the header
- [ ]  Meet with Julian to do knowledge transfer
- [ ]  Configure HTTP requests so Keycloak token can be sent to the backend
- [ ]  BackendAuth class (backend/auth/backend.py) is re-coded to correctly check for new token's roles
- [ ]  WALLY gatekeeper deployment is removed
- [ ]  Env files are updated to contain the new connection details for Keycloak (copy from frontend/.env.development)

**Additional Context:**
I have left extra logging and commented out old logic for reference/debugging that should be removed when this ticket is closed.

Currently WALLY assumes that it is getting its authentication done by a proxy and then being returned info it needs in the headers of the HTTP request.  That can no longer be the logic in order to move to the gold realm.  

The app on my branch is no longer connected to the proxy.  It is now connecting directly to the dev environment of the keycloak gold realm.  The frontend is working as intended, getting the returned token and displaying the correct name at the top of the page.  However the backend has no way of seeing the token anymore and is not designed to do its own authentication.  

So for next steps there should be a way to configure HTTP requests to include the token in the header for the backend to be able to handle it accordingly.  Next is to read the documentation on Starlette's authentication middleware and configure our AuthBackend in backend/auth/backend.py to handle the new token accordingly instead of assuming authentication is done automatically.  Once that is done; the app should be good to go when it comes to the gold realm; before deploying though it is imperative to make sure the database (part of the next ticket) can handle the new token structure.  So the definition of done on this ticket is for authentication to be working locally.

- The Keycloak gold realm is [here](https://bcgov.github.io/sso-requests/my-dashboard/integrations) and it already contains the wally-view role in dev which is what should be checked for authenticating users to see the app.
- Removing the gatekeeper is simply deleting the files for it's deployment, I haven't done that in case there is info on there that is useful during the backend authentication handling.

**Comment by JulianForeman** [comment]
I added a last commit to my PR which can be worked off of; I have no idea if my approach is correct and will work but I think it gives a good point to be able to ask questions if needed.

**Comment by LolandaE** [comment]
This work is being done in WALLY ticket #702
