### ISSUE TITLE
Update Keycloak Version - WALLY

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/NRPTI#1003]
**Describe the task**
The keycloak for wally is currently running at "^6.0.1" which is wildly outdated as the current version is 20.0.0.  This should be updated before the realm is moved to gold to assure there are no errors caused by outdated commands/fields.

**Acceptance Criteria**
- [ ] Change package.json to "^20.0.0"
- [ ] Install updated package.json
- [ ] Test locally to check for authentication errors
- [ ] Record bugs and create a new ticket to address them

**Additional context**
- The module to update in package.json is called keycloak-js

**Comment by LolandaE** [comment]
Wally #659 created so it's in the correct repo. Closing this ticket as it's now a duplicate.
