### ISSUE TITLE
Delete CSV file - NRPTI

### ISSUE THREAD

**Issue by LolandaE** [bcgov/NRPTI#1027]
**Describe the task**
Delete an error-filled CSV file from NRPTI database. Date is December 18 2023, Only record with that date.

**Purpose**
The uploaded file was filled with errors. If not possible to upload a corrected document, the best solution is to delete the CSV.

**Acceptance Criteria**
- [ ] CSV file with errors is removed from NRPTI

**Additional context**
- record could be in two places - mongodb and amazon s3 buckets
- try creating document in staging environment and delete it. if no side effect, delete in prod
- alternate plan: change the date of record, then remove the data from the record
- Info from Jack:
The issue is fortunately not a functionality issue, but instead it's a data issue. One of our users uploaded a csv file with many many errors. We are looking into this, but it's likely not possible for us to uploaded a corrected document (which would be the ideal way to fix this). What we're hoping for is for the csv file itself to be deleted in NRPTI.
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/593a41a4-0efc-4ae8-b3aa-bfc5ed74c716)

**Comment by RFK250** [comment]
Additional context: 

The files in question have the Source=agri-cmdb-csv, and the date stamps below:
![image](https://user-images.githubusercontent.com/86069412/228623900-9154375a-7917-4296-ad78-243f9ba392d1.png)
