### ISSUE TITLE
NRCED SSL Cert renewal

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1029]
**Describe the task**
The NRCED SSL Cert needs to be renewed before March 22nd which is when it is set to expire, if possible we want to automate renewals for NRCED

**Purpose**
To prevent the service from having a security warning upon landing at the NRCED page

**Acceptance Criteria**
- [ ] NRCED SSL is renewed
- [ ] NRCED SSL Renewal is automated with Certbot

**Additional context**
- See also: https://github.com/bcgov/agri-nmp/blob/master/RenewCert.md

**Comment by Christopher-walsh22** [comment]
The Certbot which was running in the NRPTI/NRCED namespace was outdated and missing an update from April 2022 ([https://github.com/jujaga/certbot/commit/9eec62d3a1b763e575fa9e658dcaa61c33fcdf82](url)). Without the Subset parameter Certbot would request two separate certificates and failing renewal in the process. I have rebuilt Certbot with an up to date image which will now manage the automatic certificate renewal.

Some parameters cannot be added to Certbot's cronjob after it has been created. In this situation the subset parameter could not be added to a previously existing cronjob. Setting up a completely new instance was required.
