### ISSUE TITLE
Research how NRPTI uses Metabase

### ISSUE THREAD

**Issue by LolandaE** [bcgov/NRPTI#1032]
**Describe the task**
Research how NRPTI uses Metabase and how a new user would acquire access.

**Purpose**
Determine if NRPTI's implementation has a view into the database (JSON file).

**Acceptance Criteria**
- [ ] Dev to meet with Jane and former SO (Jack) to discuss use case

**Additional context**
- Service Owner experiences log in issues (having to do it multiple times) and is eventually able to. Not sure why Metabase does this.

**Comment by RFK250** [comment]
@jakemorr This ticket can probably get closed now that Jane has access. I also have administrative access in Metabase for NRPTI and can give anyone access who might need it.
