### ISSUE TITLE
Investigate Dev Metabase issue and fix if possible

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1043]
Currently, Metabase is functioning only in Test and Prod environments, however we currently cannot log into it.

Things we know:
- Mark Lise's email address is the only account registered as a metabase admin in Dev
- Dmitri tried to log in with command line using Mark Lise's credentials, but the password was rejected
- Mark Lise tried to log in with his credentials via the Metabase username/password UI, but his password was rejected. He is confident he used the password that was previously correct.
- Mark Lise tried to use the "Forgot your password?" UI feature, but it did not email him. He suspects the Metabase emailer function is not working properly.

Desired outcome:
- An admin can log into the Dev Metabase and can add other admins.
- If this is not addressed, SO business analysts will not be able to assist developers in analyzing data in the dev environment.

**Comment by RFK250** [comment]
@jakemorr I would not consider this to be a priority until work resumes on NRPTI importers. There was definitely a use case while we were investigating the NRIS-EMLI importer. In practice, the Dev Metabase is rarely used outside of times of development. A workaround whenever Metabase is needed would be to push changes to Test where we know Metabase works. It's not ideal though.

**Comment by LocalNewsTV** [comment]
Accessed database that metabase was using, injected self into the user list, added sustainment team email to list of users.
Mark Lise's account no longer existed in the user database, so he was unable to login for that reason
