### ISSUE TITLE
Ability for a NRPTI admin to update Issuing Agency values for Ministry of Agriculture

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1045]
User Story:
As an administrative user of NRPTI, I want to be able to update Issuing Agency values in UIs, importers and records when ministry names change so that I do not have to submit a development request.

Description:
Government frequently undergoes reorganizations and name changes. When those occur, three other things must happen:
1. existing NRPTI records must be updated to reflect those, 
2. NRPTI UI instances (e.g. add/edit record UIs, search/filter UIs, custom BCMI UIs) need to be updated, and 
3. Importers must also be updated to ensure new records are not created with old values.

Currently, there is no user interface to do this.

Scope:
This user story does not include cases where ministry names need to be added, subtracted, or combined. While those are genuine use cases, they happen less frequently, are more complex than simply changing values, and in any case likely cannot be addressed until this user story is addressed anyways.

Acceptance Criteria:

NRPTI:
- [x] Write a migration to add the ApplicationAgency names into the NRPTI db
- [x] Write a migration to update all `issuingAgency` names to their `agencyCode`s
- [x] I should be able to change an agency's name from a separate UI ("Agencies")
- [x] The correct agency name should appear in the "Agencies" UI
- [x] The correct agency name should appear for each individual record in NRPTI under "Issuing Agency"
  - [x] Administrative Penalty
  - [x] Administrative Sanction
  - [x] ~Agreement~ (issuing agency not in record)
  - [x] Annual Report
  - [x] Certificate
  - [x] Certificate Amendment
  - [x] Construction Plan
  - [x] Court Conviction
  - [x] Correspondence
  - [x] Dam Safety Inspection
  - [x] Inspection
  - [x] Management Plan
  - [x] Order
  - [x] Permit
  - [x] Restorative Justice
  - [x] Report
  - [x] Compliance Self-Report
  - [x] Ticket
  - [x] Warning 
- [x] When I select "Add Record" (or "Edit" a record), I should see the correct agency name under "Issuing Agency":
  - [x] Administrative Penalty
  - [x] Administrative Sanction
  - [x] ~Agreement~ (issuing agency not in record)
  - [x] Annual Report
  - [x] Certificate
  - [x] Certificate Amendment
  - [x] Construction Plan
  - [x] Court Conviction
  - [x] Correspondence
  - [x] Dam Safety Inspection
  - [x] Inspection
  - [x] Management Plan
  - [x] Order
  - [x] Permit
  - [x] Restorative Justice
  - [x] Report
  - [x] Compliance Self-Report
  - [x] Ticket
  - [x] Warning
- [ ] When importing, the correct agency name should appear for each record that is imported by "Imports":
  - [x] EPIC imports
  - [x] NRIS-EPD imports
  - [x] NRIS-EMLI imports
  - [ ] CORE imports
  - [x] BCOGC imports
  - [x] ALC
  - [ ] AMS
  - [ ] AGRI-CMDB
  - [ ] AGRI-MIS
  - [x] COORS
  - [ ] NRO-ERA
- [x] When viewing the "Open Advanced Filters", I should see the correct agency name in "Responsible Agency" dropdown filter
- [x] The correct agency name should appear in Mine Records under Mine List
- [x] The correct agency name should appear in Mine Records > Add New Record > Agency Dropdown
- [x] The correct agency name should appear in Mine Collections > Create New Collection > Agency Dropdown
- [x] Only `sysadmin` users should be able to change an agency name from NRPTI 
- [x] Migrate records with {_schemaName:"CollectionBCMI"} to use Agency Code 

NRCED:
- [x] The correct agency name should appear in the records on NRCED

BCMI
- [x] The correct agency name should be reflected in the records on BCMI
- [x] The correct agency name should be reflected in the list of records on BCMI
- [x] The correct agency name should appear for each individual record in NRPTI
  - [x] Annual Report
  - [x] Certificate
  - [x] Certificate Amendment
  - [x] Construction Plan
  - [x] Correspondence
  - [x] Dam Safety Inspection
  - [x] Inspection
  - [x] Management Plan
  - [x] Order
  - [x] Permit
  - [x] Report
- [x] When I "Add New Record" to a mine, I should see the correct agency name in the different types:
  - [x] Annual Report
  - [x] Certificate
  - [x] Certificate Amendment
  - [x] Construction Plan
  - [x] Correspondence
  - [x] Dam Safety Inspection
  - [x] Inspection
  - [x] Management Plan
  - [x] Order
  - [x] Permit
  - [x] Report
- [x] When viewing the "Open Advanced Filters", I should see the correct agency name in "Responsible Agency" dropdown filter

Notes:
- Do one agency at a time. Start with Ministry of Agriculture.
- Currently, Issuing Agency values are stored as constants [here](https://github.com/bcgov/NRPTI/blob/6ec2189bc8c9e4ae543d94f93b9e27a9f355b504/api/src/utils/constants/misc.js#L22).
- A baseline acceptable increment would allow a system admin user to (a) navigate to a screen viewable only by a system admin, (b) view the constant labels (e.g. `AGENCY_ALC`, etc) and their current values (e.g. `Agricultural Land Commission`, etc.) in adjacent open text boxes, (c) edit those values, and (d) save changes.
![image.png](https://images.zenhubusercontent.com/621d43d01fb9602d483b99b3/7c3823cc-a9fd-4b94-a863-ef1256d7871f)
- Issuing Agency names are also sometimes assigned by importers (e.g. COORS importers will contextually assign issuing agency names based on certain data values)

QA
- [X} New issuing agency value appears in NRPTI UI and drop-down menus
- [X] New issuing agency value is assigned when a new record is created

The below list is for when I changed an issuing agency and then checked existing records for the change.

- [X] Agricultural Land Commission
- [x] BC Wildfire Service - did not update to "BC Wildfire Service Test"
- [x] Conservation Officer Service - did not update to "Conservation Officer Service Test"
- [x] Environmental Assessment Officer - did not update to "Environmental Assessment Office Test"
- [x] Ministry of Energy, Mines and Low Carbon Innovation - did not update to "Ministry of Energy, Mines Test" - _but_ originally when I started testing, it showed "Ministry of Energy and Mines" and I updated it to "Ministry of Energy, Mines and Low Carbon Innovation" - so it worked once
- [x] Ministry of Environment - I renamed the first instance in the drop-down list to "Ministry of Environment 1" and the second instance to "Ministry of Environment 2", but cannot find those new values - however, I _did_[ find issuing agency values with "Ministry of Environment and Climate Change Strategy"](https://nrced-f00029-dev.apps.silver.devops.gov.bc.ca/records;act=Environmental%20Management%20Act;activityType=AdministrativePenaltyNRCED) which does not even display in the drop down list.
- [x] BC Parks - did not update to "BC Parks Test"
- [x] BC Energy Regulator - did not update to "BC Energy Regulator Test"
- [x] LNG Secretariat - Skipped as it does not appear in NRCED
- [x] Ministry of Agriculture and Food - did not update to "Ministry of Agriculture Test"
- [x] Ministry of Forests - did not update to "Ministry of Forests Test"
- [x] Natural Resource Officers - did not update to "NRO Test"
- [X] Ministry of Water, Land and Resource Stewardship - I changed the value, and then discovered there were no records. So I created one, and it used the new value. Then I tried changing it, and it worked.
- [x] Climate Action Secretariat - did not update to "CAS Test"

**Comment by RFK250** [comment]
@jakemorr This user story was always in the NRPTI backlog right from MVP, but it was not (and still is not) as important as stories to automate data importing and/or onboard new data sources.

**Comment by davidclaveau** [comment]
Created a Update Issuing Agency component and started on the preliminary changes for the model and migration. An initial migration was created to insert an `agencyCode` and `agencyName` as a separate `_schemaName: ApplicationAgency`.

Weird issue with the connection not closing after the migration, so that needs to be considered before moving forward. Also need to work on the migration to change all references to the Agencies (eg. `issuingAgency`) to the new `agencyCode`. A work in progress!

**Comment by davidclaveau** [comment]
Created a component to allow the user to change an agency's name from the NRPTI admin page. This sends a `put` request to the api which in turn finds the relevant `agencyCode` and updates the `agencyName` in the db.

There are a few places where an agency's name is hard-coded in the codebase. To circumvent this, we added `ApplicationAgencyService` to `FactoryService` to run on `APP_INITIALIZER`, so the app pings the api and checks _once_ to retrieve the new agencyNames. The app can retrieve the agency list from this class and no longer relies on the hard-coded agency list from `Utils` to display the agency's name. After a user updates an agency's name, we then refresh the agency list in ApplicationAgencyService.

NRPTI requires some substantial linting updates (running the linting-update command locally changes ~440 files).

**Comment by davidclaveau** [comment]
Created a component to allow the user to change an agency's name from the NRPTI admin page. This sends a `put` request to the api which in turn finds the relevant `agencyCode` and updates the `agencyName` in the db.

There are a few places where an agency's name is hard-coded in the codebase. To circumvent this, we added `ApplicationAgencyService` to `FactoryService` to run on `APP_INITIALIZER`, so the app pings the api and checks _once_ to retrieve the new agencyNames. The app can retrieve the agency list from this class and no longer relies on the hard-coded agency list from `Utils` to display the agency's name. After a user updates an agency's name, we then refresh the agency list in ApplicationAgencyService.

NRPTI requires some substantial linting updates (running the linting-update command locally changes ~440 files).

**Comment by davidclaveau** [comment]
NRPTI:
- [x] I should be able to change an agency's name from a separate UI ("Agencies")
- [x] The correct agency name should appear in the "Agencies" UI
- [ ] The correct agency name should appear for each individual record in NRPTI
  - [ ] Administrative Penalty
  - [ ] Administrative Sanction
  - [ ] Agreement
  - [ ] Annual Report
  - [ ] Certificate
  - [ ] Certificate Amendment
  - [ ] Construction Plan
  - [ ] Court Conviction
  - [ ] Correspondence
  - [ ] Dam Safety Inspection
  - [ ] Inspection
  - [ ] Management Plan
  - [ ] Order
  - [ ] Permit
  - [ ] Restorative Justice
  - [ ] Report
  - [ ] Compliance Self-Report
  - [ ] Ticket
  - [ ] Warning 
- [ ] When I select "Add Record", I should see the correct agency name:
  - [ ] Administrative Penalty
  - [ ] Administrative Sanction
  - [ ] Agreement
  - [ ] Annual Report
  - [ ] Certificate
  - [ ] Certificate Amendment
  - [ ] Construction Plan
  - [ ] Court Conviction
  - [ ] Correspondence
  - [ ] Dam Safety Inspection
  - [ ] Inspection
  - [ ] Management Plan
  - [ ] Order
  - [ ] Permit
  - [ ] Restorative Justice
  - [ ] Report
  - [ ] Compliance Self-Report
  - [ ] Ticket
  - [ ] Warning
- [ ] When importing, the correct agency name should appear for each record that is imported by "Imports":
  - [ ] EPIC imports
  - [ ] NRIS-EPD imports
  - [ ] NRIS-EMLI imports
  - [ ] CORE imports
  - [ ] BCOGC imports
  - [ ] ALC
  - [ ] AMS
  - [ ] AGRI-CMDB
  - [ ] AGRI-MIS
  - [ ] COORS
  - [ ] NRO-ERA
- [ ] When viewing the "Open Advanced Filters", I should see the correct agency name in "Responsible Agency" dropdown filter

NRCED:
- [ ] The correct agency name should appear in the records on NRCED

BCMI
- [ ] The correct agency name should be reflected in the records on BCMI
- [ ] The correct agency name should appear for each individual record in NRPTI
  - [ ] Annual Report
  - [ ] Certificate
  - [ ] Certificate Amendment
  - [ ] Construction Plan
  - [ ] Correspondence
  - [ ] Dam Safety Inspection
  - [ ] Inspection
  - [ ] Management Plan
  - [ ] Order
  - [ ] Permit
  - [ ] Report
- [ ] When I "Add New Record" to a mine, I should see the correct agency name in the different types:
  - [ ] Annual Report
  - [ ] Certificate
  - [ ] Certificate Amendment
  - [ ] Construction Plan
  - [ ] Correspondence
  - [ ] Dam Safety Inspection
  - [ ] Inspection
  - [ ] Management Plan
  - [ ] Order
  - [ ] Permit
  - [ ] Report
- [ ] When viewing the "Open Advanced Filters", I should see the correct agency name in "Responsible Agency" dropdown filter

**Comment by RFK250** [comment]
Nice checklist. :) BTW, I think you're going to find that some of those record types do not use an issuing agency, especially ones built specifically for BCMI.
