### ISSUE TITLE
Upgrade Metabase

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1052]
NRPTI still uses Metabase v0.41.6 and has not been upgraded in ~1.5 years. Starting with v0.46, Metabase includes enhanced features for MongoDB databases that will improve administrative user abilities to produce business analytics. Currently, many common database analysis functions are not available to MongoDB databases like NRPTI.

Most recent version is 0.47 as of Aug 29, 2023.

![image.png](https://images.zenhubusercontent.com/621d43d01fb9602d483b99b3/0f1ec0d1-077f-414f-90b0-8ee2fb2980d3)

Instructions to upgrade are [here](https://www.metabase.com/docs/v0.46/installation-and-operation/upgrading-metabase).

![image.png](https://images.zenhubusercontent.com/621d43d01fb9602d483b99b3/9b869f57-f66d-4921-bc0e-74c09ed5f1bd)

**Additional Context**
- NRPTI uses older version of mongoDB - potential for compatibility issues or dependencies
- [Confluence page for NRS Metabase instances](https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Metabase)

**Comment by RFK250** [comment]
@jakemorr This should be an uncomplicated ticket that has value for me and other NRCED administrators.

**Comment by LolandaE** [comment]
@RFK250 - This ticket may be a little more complicated since we are updating from an older version, there may be dependencies.

**Comment by sanjaytkbabu** [comment]
Metabase in DEV is upgraded to 0.47.9: https://metabase-f00029-dev.apps.silver.devops.gov.bc.ca/
Waiting on approval from Robin Malafry to proceed with TEST & PROD deployment. Robin & Kyle are on vacation until January 5.
Readme has been updated with upgrade steps.

**Comment by sanjaytkbabu** [comment]
PROD has been upgraded and confirmed working with Robin.
