### ISSUE TITLE
NRIS-FLNR-CSV importer not publishing new records

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1054]
Currently:
- NRIS-FLNR-CSV importer has been stuck at 6405 records since Dec 14, 2022, despite showing as "completed"

Expected behaviour:
- NRIS-FLNR-CSV importer should be importing and publishing new records very regularly, often daily. Ministry of Forests staff confirms that new records have continued to be closed in the NRIS source system regularly since that date, so it should not be stuck at 6405.
 
Risk:
- Until fixed, Ministry of Forests inspections will not be published to NRCED. This could lead the public or media to believe that Forests has not performed any inspections since December. The possible impact is therefore poor optics.

![image.png](https://images.zenhubusercontent.com/621d43d01fb9602d483b99b3/2441119f-bf72-4486-81e7-e7c14cf87364)

Notes:
- NRIS-FLNR-CSV importer works differently from the other NRIS importers, as it does _not_ use the NRIS Web Service to pull data. It instead uses an instance of FMS Server.
- FMS Server runs in Zone B and on a daily basis reads data from NRIS (aka CVIS, the name of the old SQL database that NRIS still uses), performs data transforms, and then we think pushes data from Zone B to NRPTI in OpenShift.
- FMS Server has run presumably untouched for two years, so it may just need a reboot and/or a software update.

**Comment by RFK250** [comment]
@jakemorr To you for prioritization.

**Comment by LolandaE** [comment]
This has started working again without needing to fix.
