### ISSUE TITLE
Add new legislation description for orders

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1085]
**Describe the task**
BC Parks would like to start publishing a new type of Order, and an additional legislation description needs to be added for it to show up properly on NRCED

**Purpose**
This ticket enables a new use case for a new set of users. Descriptions provide NRCED users with context about a statute in an compliance and enforcement action. These are baked in to NRPTI so that all actions with the same legislation show the same text.

**Acceptance Criteria**
- GIVEN I am a NRPTI user 
- AND I have navigated to the "[Add new order screen](https://nrpti-f00029-prod.apps.silver.devops.gov.bc.ca/records/orders/add)" (OR am editing an existing order)
- AND I have clicked "Add new legislation"
- WHEN I enter `Act = Park Act` AND `Regulation = Park, Conservancy and Recreation Area Regulation` AND `Section = 9`
- THEN the Description field is automatically populated with the text "Order to leave a park, conservancy or recreation area"

![image.png](https://images.zenhubusercontent.com/621d43d01fb9602d483b99b3/4b1dcbf4-ac07-4926-a41b-0d028915361c)

**Comment by sanjaytkbabu** [comment]
Legislation description added and PR created

**Comment by RFK250** [comment]
Awesome, thanks @sanjaytkbabu !

**Comment by sanjaytkbabu** [comment]
PR merged and rolled out to test

**Comment by RFK250** [comment]
@sanjaytkbabu 
Verified on NRPTI in Test
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTlNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a8d8436a349e4e03fa3fe81fe08dd7daf4f5d122/image.png)

And verified on NRCED in Test
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak5NIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc082fdbf53889b45e35e61f28283f6d5aea5d76/image.png)

**Comment by sanjaytkbabu** [comment]
Deployed to PROD
