### ISSUE TITLE
Correct Extra Fish and Seafood Act Inspections

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1103]
**Describe the task**
Show only the correct Fish and Seafood Act Inspection records, or wipe all Fish and Seafood Act Inspection records so that the user can re-upload correct ones.

**Purpose**
In #1027, there was an attempt to correct tens of thousands of extra records that were created when a user accidentally uploaded a CSV generated from the wrong query. I don't recall what the solution was - I think it was a migration. However, there are still a thousand or so erroneous records being displayed (there should only be about 983 total). In other words, [there are currently 1891 Fish and Seafood Act Inspection records being displayed to users](https://nrced.gov.bc.ca/records;activityType=InspectionNRCED;act=Fish%20and%20Seafood%20Act;ms=71;currentPage=1;pageSize=100;sortBy=-dateIssued), but only 983 are valid and the remaining 908 are invalid.

**Acceptance Criteria**
At this point, it would be acceptable to run a migration to simply wipe all Fish and Seafood Act Inspections from production and have the user be able to upload a fresh CSV file. This would not impact users in any appreciable way.

Notify Kyle and Robin prior to wiping all Fish and Seafood Act Inspections.

**Additional Notes**
- This should be limited to Fish and Seafood Act Inspections. There are other Fish and Seafood Act records such as Tickets - those should be left untouched.

**Comment by davidclaveau** [comment]
Added a migration to delete all of the Fish and Seafood Act inspections for `production` only, which means this migration will only run once. Kyle and Robin will add back the corrected data at a later date.
