### ISSUE TITLE
Update packages deemed Critical for NRPTI API

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1149]
**Describe the task**
Run NPM Audit to assess what packages need to be updated and assess severity, and look to address critical level package updates.

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] When we run NPM Audit no packages are marked as critical unless deemed acceptable
- [ ] packages are compatible with Typescript
- [ ] changes to the codebase made where necessary

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by acatchpole** [comment]
deployed to prod
