### ISSUE TITLE
Update NRPTI CI-CD to reflect our board

### ISSUE THREAD

**Issue by pinkyandthekane** [bcgov/NRPTI#1154]
**Describe the task**
We want to have a CI-CD pipeline that reflects the development workflow we follow for tackling tickets.

**Purpose**
Purpose is to improve the developer experience.

**Acceptance Criteria**
- [ ] Tech review of Jenkins/GitHub actions/other alternatives and document this
- [ ] Implement the CI-CD pipeline as shown in the diagram below on the desired platform

**Additional context**
- Be cognizant of the fact that this is a migration, so we will need to validate functionality against current pipeline at each stage

**Comment by sanjaytkbabu** [comment]
[Uploading... MicrosoftTeams-image.png]

**Comment by fergmac** [comment]
The most straight forward approach is to use GitHub webhook flow with Tekton pipelines.

I don't think dockerizing the frontend is a requirement. We appear to have the required BuildConfigs inside OpenShift. Using the s2i build strategy. If we were starting from scratch it could make sense to dockerize the front end and use the docker build strategy.

Tests are currently being handled with GitHub Actions.
SonarCloud appears to be handled by GitHub as well though there is no explicit SonarCloud workflow included in the repository.

Currently we are running the builds for:

- nrpti (web) this is a collection of apps using the app label in OpenShift?
- public-nrced (web)
- nrpti-api

**Steps to migrate:**

We need to update the related BuildConfigs in OpenShift to 

- add a trigger for type GitHub

Then complete the following steps:

- add a github secret to OpenShift secrets
- update this [URL](![Image](https://github.com/bcgov/NRPTI/assets/20193291/d98d6571-4d79-4a2a-a784-f30b93e6171b))
- go to [GitHub repo > Settings > Webhooks](![Image](https://github.com/bcgov/NRPTI/assets/20193291/1fbcb1e3-66ab-4b67-b7f2-81ed75c432c9))
- create webhook using the above URL and the GitHub secret generated in OpenShift

We can create Tekton Pipelines in OpenShift to handle retagging the image and deploying to staging and production. Currently we do this manually:

`

![Image](https://github.com/bcgov/NRPTI/assets/20193291/63d1beab-c35a-4659-a912-7038e1ac8d79)

`

**Comment by fergmac** [comment]
[Sonarcloud](https://sonarcloud.io/organizations/bcgov-sonarcloud/projects) is setup at the organization level.

**Comment by fergmac** [comment]
In OpenShift we currently have an `angular_app_build` which builds first. The following three builds take the  `angular_app_build` as input: 

- `admin-nrced-build`
- `public-nrced-build`
- `public-lng-build`

We only need to add the trigger for the github webhook to the `angular_app_build` and the above 3 builds should trigger.

**Comment by LocalNewsTV** [comment]
When I was doing my capstone project, we added hooks that sent alerts to teams on Success/Failure
It might be beneficial to put notifications in Teams for Success/Failures.
 
It's worth noting that we never did get the Failure notification to properly work, as it wasn't a priority, so it didn't fire
 
I'm including the Actions we had for the API since the notifiers were at the bottom
[Our GH Action](https://github.com/bcgov/citz-imb-wayfinder/blob/main/.github/workflows/api-build-deploy.yaml)

Kind of a replacement for the Jenkins ones, but using teams instead of clogging emails. And you don't have to update the email list
