### ISSUE TITLE
Update BCOGC importers to reflect new act title, using BC Laws API if possible

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1179]
**Describe the task**
Update BCOGC importers to use "Energy Resource Activities Act" instead of "Oil and Gas Activities Act" - ideally, using the [BC Laws Restful API](https://www.bclaws.gov.bc.ca/civix/template/complete/api/API_document.html) to do it.

**Purpose**
1. When the BC Oil and Gas Commission got renamed to BC Energy Regulator, the name of its parent act was also changed (see description above) - this needs to be changed in NRCED to reflect this.
2. Currently, the names of acts and regs are hard coded into records. Since NRPTI/NRCED was developed, the BC Laws API has been released. If we use that API to get data for NRCED records on import, then whenever an act changes names (rare) or a section number is changed (more common), then it decreases the risk that development work will be needed just to change those things. This is valuable because it automates a change, reducing costs and effort, and maintains the accuracy of records on NRCED.

**Acceptance Criteria**
- GIVEN I am a NRCED user viewing https://nrced.gov.bc.ca/records
- WHEN I view a BCOGC record (in list or detail view)
- THEN I see "Energy Resource Activities Act" instead of "Oil and Gas Activities Act"
- AND WHEN I click on the "Issued under which Act" filter
- THEN I see "Energy Resource Activities Act" instead of "Oil and Gas Activities Act"
- AND WHEN I click on "Export to CSV" and open the resulting record
- THEN I see "Energy Resource Activities Act" instead of "Oil and Gas Activities Act"

- GIVEN I am a NRPTI user viewing https://nrpti-f00029-prod.apps.silver.devops.gov.bc.ca/records
- WHEN I click on the "Issued under which Act" filter
- THEN I see "Energy Resource Activities Act" instead of "Oil and Gas Activities Act"

Additional AC for using BC Laws API
- WHEN the [BCOGC importers](https://github.com/bcgov/NRPTI/tree/master/api/src/integrations/bcogc) create or update a record in NRPTI
- THEN values for Act, Section, Subsection and Paragraph are obtained via the BC Laws API.
(Note I would accept a first increment of just using the API to get the title of the act, and then we can iterate later on section, subsection and paragraph).

**Additional context**
- **Critical question that would need to be answered first**: is there an approach that can use the values obtained through the BC Laws API to write data to BCOGC records without having to change _all_ other importers? i.e. can we get "Energy Resource Activities Act" from the BC Laws API and put that value into the Act metadata without needing an intermediate variable like we did with Issuing Agency values? Because if we need to use an intermediate variable, this becomes a huge task. But if we can just write the value we get from the API straight into the record, it should be a small task.
- The XML for the the title of the Act can be called with [https://www.bclaws.gov.bc.ca/civix/content/complete/statreg/667588372/08036/](https://www.bclaws.gov.bc.ca/civix/content/complete/statreg/667588372/08036/)
- CIVIX_DOCUMENT_TITLE should return the correct title (you may also be able to get the title from the Document xml below)

- The XML for the Energy Resource Activities Act can be called with [https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/08036_01/xml](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/08036_01/xml)
- The XML tag for the title is `<act:title>Energy Resource Activities Act</act:title>`

- The XML has unique IDs for sections, subsections and paragraphs. For example: BCOGC inspection records have Section = 57 and subsection = (4).  `<bcl:section id="d2e6157">` should return `<bcl:num>57</bcl:num>` and  `<bcl:subsection id="d2e6241">` should return `<bcl:num>4</bcl:num>`

- Note: The Oil and Gas Activities Act used to have `CIVIX_DOCUMENT_ID = 08036_01`; when government changed the name of the act, the document was updated to reflect the new title, and a new document was created for the Oil and Gas Activities Act with `CIVIX_DOCUMENT_ID = 08036a_01`. That approach means that it should be safe to continue to use `CIVIX_DOCUMENT_ID = 08036_01` no matter how often government changes the name of the act. Dev work would only be needed if a new CIVIX_DOCUMENT_ID was used.

**Comment by acatchpole** [comment]
Current strategy :
- Update the hard-coded values to satisfy this ticket.
- Create two new tickets:
   1. Create a new collection in the database to store all the relevant legislation data that is currently hardcoded and update the importers and front end elements to read from this collection
   2. create a scheduled process where those values are updated based on calls to the BC Laws API

**Comment by RFK250** [comment]
I love this approach not just because it solves the immediate problem and sets the stage for avoiding it in the future, but also because in the long run it opens the door to a future ticket to automatically get descriptions through via the API from regulations [like this one](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/89_97_03). Lots of potential value there in improved workflows, automation, and a consistent user experience. Stay on this path. :) 

cc @malafry @jakemorr you should consider exploring this at the user story level.

**Comment by sanjaytkbabu** [comment]
Deployed to dev: https://nrpti-f00029-dev.apps.silver.devops.gov.bc.ca

**Comment by RFK250** [comment]
It looks like all the all the AC are met! @jakemorr  I would accept this ticket. cc @malafry

**Comment by sanjaytkbabu** [comment]
deployed to prod
