### ISSUE TITLE
Update "NRPTI/NRCED Information" Document in 'Dev Chat' 

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/NRPTI#1183]
**Describe the task**
Update "NRPTI/NRCED Information.docx" Document in 'Dev Chat' 

**Purpose**
Not all information and tips need to be documented in a public facing repo. But with developers cycling through Sustainment team its valuable to keep this information for the next generation of developers to consume when working in these spaces

**Acceptance Criteria**
- [ ] Information Cleaned up, Updated and Added to in Document
- [ ] Headers used appropriately
- [ ] Table of contents updated (it's a single button press)

**Additional context**
- You can add tips involving setups, weird nuances, or advice if future tickets may impact an area you worked on
- GWELLS currently has a pretty up to date one, for reference

**Comment by sanjaytkbabu** [comment]
document updated
