### ISSUE TITLE
Minor typos in HTML

### ISSUE THREAD

**Issue by RFK250** [bcgov/NRPTI#1185]
**Describe the task**
Update HTML of the NRCED landing page and records page to ensure users see "Natural Resource Compliance & Enforcement Database"

**Purpose**
Currently, there are inconsistent displays of the title, including "Resource" or "Resources" and "and" or "&" depending on where you look.

**Acceptance Criteria**
GIVEN I am viewing the title of the database
THEN I see the phrase "Natural Resource Compliance and Enforcement Database"

**Additional context**
Pages: [here ](https://nrced.gov.bc.ca/)and [here](https://nrced.gov.bc.ca/records)
Fixes:
1. Top left of both pages (remove the "s" and change "&" to "and")
<img width="405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzIrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f0d55ce7e83226c8e5232774383da511d18b72f/image.png" alt="image.png" />

2. Title on Records page (remove the "s")
<img width="1106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3UrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50ec2fd769bed0ceee2f07ba6bb7c91c91c2f25b/image.png" alt="image.png" />

**Comment by davidclaveau** [comment]
Very straightforward changes to the HTML and a few TypeScript files where there was erroneous or incorrectly formatted text. Also added some updates to the `migrations` README.
