### ISSUE TITLE
NRCED SSL Cert Renewal - Expires Mar 22

### ISSUE THREAD

**Issue by LolandaE** [bcgov/NRPTI#1203]
**Describe the task**
The NRCED SSL Cert needs to be renewed before March 22nd which is when it is set to expire. If possible we want to automate renewals for NRCED.

**Purpose**
To prevent the service from having a security warning upon landing at the NRCED page.

**Acceptance Criteria**
- [x] NRCED SSL is renewed
- [ ] NRCED SSL Renewal is automated with Certbot

**Additional Context**

Refer to this: https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR?

Entrust Cert Creation: https://bcgov.sharepoint.com/:w:/r/teams/05196-DevChat/Shared%20Documents/Dev%20Chat/1-How-to%27s/Entrust%20Cert%20Creation.docx?d=w6558f263604b4946b11e1e808e0c409d&csf=1&web=1&e=FPHr3Z

See also: https://github.com/bcgov/agri-nmp/blob/master/RenewCert.md

Comment from [last Cert renewal](https://github.com/bcgov/NRPTI/issues/1029):
NRCED is now running with the new version of CERTBOT which will manage renewals in the future. The BC Mines team also having routes managed in our namespace is using the same setup of CERTBOT. This should not cause any issues for either team so long as CERTBOT stays up to date.

**Comment by davidclaveau** [comment]
Created a CSR ticket with the NRIDS team, providing with the iStore Billing information for NRPTI. Should expect to hear back from the team and be able to move forward with applying the new certificates to the nrced.gov.bc.ca domain.

**Comment by davidclaveau** [comment]
NRCED has been updated with the new certificate and is set to expire March 22, 2025

![Image](https://github.com/bcgov/NRPTI/assets/62899351/8363ab03-bd22-4261-8897-d3a9a1ceb305)
