### ISSUE TITLE
Turn on EMLI Automated Importer requirements

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1217]
**Problem Description** 
**In order to** turn on automated inspection record uploads from NRIS, we need to turn on the importer responsible however the query it uses to pull records from NRIS would need to be reviewed to insure it would not pull records with harms.

**Timebox**
- until complete

**Outcome**
- The work is clearly laid out in as many tickets as required, (could just be updating #1125
- any documentation related to this importer is highlighted in the resulting tickets.
- Logic and importer parameters provided to Mines Director of Digital Services in advance of work beginning on importer. 
- Ensure this importer is covered by the test suite
- Enough information for PO to make decision on funding requirements and proposed September deadline

**Additional Context**
- Starting April first all inspections will be Harms reviewed and in NRIS, so we can move with confidence that NRCED wouldn't be releasing inappropriate data
- Mines executive wants automated upload of these record to NRCED in place by September.

As a NRCED user interested in mining operations, I want to be able to view the inspection reports for mines so that I can understand how the mine is operating and feel confident that government is holding mining companies accountable.

As a Mines inspector, I want ONLY inspection reports that are reviewed and redacted to be published to NRCED so that we remain compliant with the Mines Act.

Additional Context
- EMLI inspections are stored on NRIS
- It is possible to import those reports using the NRIS Web Service, but they are currently not being published
- It is not acceptable to simply publish just any attachments associated with an EMLI NRIS record - only reviewed, redacted and finalized attachments should be published
- Review and redaction of inspection reports is currently conducted by EMLI staff. It's a fully manual process that ends with a redacted copy of the original inspection report being created.
- There is no function in NRIS that would allow an NRIS user to differentiate publishable attachments from non-publishable attachment (This is solved by the date)

**Comment by sanjaytkbabu** [comment]
API called for obtaining nris-emli records: "https://api.nrs.gov.bc.ca/nrisws-api/v1/emprInspections?inspectionStartDate=2020-01-01&inspectionEndDate=2020-01-15"
inspectionStartDate: 2020-01-01 (Hardcoded)
inspectionEndDate: 2 weeks from start date, for every subsequent call this is incremented 7 days until end date reaches current date.

The following checks are done to find valid complete records that are >= 7 days:
//Only import assessmentSubStatus in 'Closed', 'Response Received' or 'Report Sent'
 const validassessmentSubStatus = ['Closed', 'Response Received', 'Report Sent'];
// For 'Response Received' and 'Report Sent' only import records that are 45 days old
if (validassessmentSubStatus.slice(1).includes(record.assessmentSubStatus) && reportDateAge < 45) return false;
//reject if inspection type isn't Mine Inspection:
if (record.inspection.inspectionSubType !== 'Mine Inspection') return false;
// reject if assessmentSubType isn't Compliance Review or Inspection
if (record.assessmentSubType !== 'Compliance Review' && record.assessmentSubType !== 'Inspection') return false;
//reject if inspectionSubType is audit
if (record.inspection.inspectionType[0] === 'Audit') return false;

This is how a valid nris-emli record looks like that is obtained via the api call.
[valid-record.json](https://github.com/bcgov/NRPTI/files/14924147/valid-record.json)
