### ISSUE TITLE
Permissions not working as expected

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1219]
**Describe the Bug**
user permissions on NRPTI specifically around admin:env-epd seem to have prohibitive rules in combination with admin:nrced and Sysadmin roles

**Expected Behaviour**
when a user has multiple permission they should have the abilities of all the permissions they are granted

**Actual Behaviour**
a user with public and Admin:Nrced permissions was not able to edit records when they were additionally granted the admin:env-epd permission. 

env-epd required to upload the order record under the environmental management act
it uploaded to LNG but not NRCED, so they needed to use their edit access granted from admin:Nrced but it wasnt available until the epd access was revoked. 

**Implications**
Creates complicated interactions for service owner and users to understand what permissions they need at a given time. rather than the permissions just adding to eachother.

**Additional Context**
- Instead of a "failed to save record" error, the user received a "Server Error: [object ProgressEvent]"
- this may be 2 bugs 1 is the permissions stuff, but the other is the record uploading to LNG instead of NRCED

**SEPARATE ISSUE THAT MAY BE RELATED:** (does not need to be solved in this ticket)
- admin:env-epd can now publish/unpublish records (1146) focus is now on manually entered records and the fact that they didn’t get correct user roles when entered by a (temporary) sysadmin
desired outcome: EPD users can edit other EPD user records, including when entered as a (temporary) sysadmin
- if we set all EPD users to the admin:env-epd role (i.e., removing sysadmin) then everything is fine; new records can be published and then edited by other EPD users; however, previously published tickets couldn’t be edited by any EPD user, if they were published at a time when that user had sysadmin access.

**Comment by acatchpole** [comment]
fix: instead of disabling edit if you are in a low-rights role, we enable edit if you have one of the relevant roles.

This change has been deployed to prod
