### ISSUE TITLE
Add tests for NRPTI related to changes to act name handling

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1223]
**Describe the task**
Write tests in both the front end and backend that relate to previous work around changes to act name.

**Purpose**
we want to increase our meaningful test coverage for NRPTI as it has gone by the wayside for a while. 

**Acceptance Criteria**
- [ ] the bug currently does not exist, so test should pass on existing code
- [ ] set test up in a way that we can verify it fails under the proper conditions
- [ ] keep code separated into functions that can have a unit test

**Additional context**
- Tickets like this is how we want to address the gaps in out test coverages, if you see something you think should have a test call it out by create a ticket (even if its not a complete ticket)

**Comment by acatchpole** [comment]
merged to master

**Comment by acatchpole** [comment]
deployed
