### ISSUE TITLE
Investigate Core-documents integration

### ISSUE THREAD

**Issue by sggerard** [bcgov/NRPTI#1240]
The core-documents integration has not been processing any records in production for some time. Investigate if this is an issue.

Additionally the core document manager endpoint does not appear to work properly in the test environment but works in production. Work with MDS team to determine why?
https://minesdigitalservices.gov.bc.ca/document-manager

**Comment by Keegnan** [comment]
Core-documents integration was fixed by a previous dev. Was a token timeout on the core-importer. Most likely confusion between seeing no imports for a short period of time.
