### ISSUE TITLE
EMLI & EPD importers failing due to timeout

### ISSUE THREAD

**Issue by sggerard** [bcgov/NRPTI#1246]
**Describe the Bug**
NRIS-EMLI & NRIS-EPD cron imports appear to be intermittently failing in production to due to timeout errors.
"General Error Error: timeout of 2000ms exceeded". Unsure as to the cause of the error, investigation required.

**Expected Behaviour**
Importer completes successfully

**Actual Behaviour**
Fails due to unknown error

**Implications**
Records from EMLI and EPD are not being updated into NRPTI.

**Comment by acatchpole** [comment]
For the EMLI import, during the period that the import was stopping with a timeout error ("General Error Error: timeout of 2000ms exceeded"), a manual query to the API returned the following message:


![Image](https://github.com/bcgov/NRPTI/assets/113044739/d388b424-b9ec-4ccf-94d1-e9d8a0e7a614)

**Comment by acatchpole** [comment]
As of 30-06-24, both importers seem to be running, but both report a status of ```Failed```. And while the EPD importer is still reporting thousands of records imported, the EMLI one is only reporting 2. Further investigation is needed to see why the ```Failed``` error is appearing.

**Comment by acatchpole** [comment]
Despite some of the import functionality returning, [this page](https://bcgov.sharepoint.com/sites/WLRS-TEC/Lists/Critical%20Announcements/AllItems.aspx) does not have the cocacola server issue showing resolved. Further effort into resolving these issues should not be made until all issues with the NRISWS server have been resolved.

**Comment by acatchpole** [comment]
Updates to the outage page show that *some* of the affected apps have been restored, including NRIS Web Service (this was likely true yesterday, and i just missed it). As of now, the EPD importer is running and still processing records ***very*** slowly. I think it appropriate to still wait for all issues with the cocacola server to be resolved before further investigation.

**Comment by Keegnan** [comment]
The integration needs to be looked into further before fixing. The move from the Cocacola server was unplanned  failure. The new infrastructure is causing issues for us to work. Need to look into limitation and how to resolve the issue with this server.

**Comment by Keegnan** [comment]
Will need to reconfigure this ticket or rewrite.
