### ISSUE TITLE
BCMI Mines page lists related records to major mines

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#1263]
**As a** *member of the public* **I want** *to see all relevant records of a mine on BCMI without navigating elsewhere* **So That** *I can see their history of compliance*

**Additional Context**
- implement a pull from NRPTI to BCMI utilizing similar styling to what exists now to display records and the related documents for each mine on BCMI
- this is for EMLI, EPD, EAO, and EMA

**Acceptance Criteria**
- on each Mine page on BCMI, I want the related records from NRCED to appear on the mines page including documents

**Comment by Keegnan** [comment]
this will most likely be tackled by 2 devs focused on a backend and frontend work

**Comment by Keegnan** [comment]
NRPTI #1262 must be completed before taking this ticket on

**Comment by Keegnan** [comment]
Need to have a chat with dev and SO to understand further.
