### ISSUE TITLE
Investigate if Certbot renewal is automated for NRCED

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#943]
**As a** *Service Owner* **I want** *automated certificate renewals* **So That** *our digital service doesn't display "your connection is not private" messaging*

**Additional Context**
- Example from Wildfire team:
https://github.com/bcgov/wps/tree/main/openshift/certbot

The cert expired in March and magically renewed (at a later date). Prevailing theory is that Certbot is automated. but for the wrong date.

**Acceptance Criteria**
- [ ] Is Certbot automated for NRCED?
- [ ] If Certbot is automated for NRCED, does the renewal date align with the cert expiration?

**Comment by Christopher-walsh22** [comment]
NRCED currently has Certbot managing the vanity url 'nrced.gov.bc.ca'. The certificate is set to expire in March of each year. Certbot will check for renewal every Sunday, and Wednesday.
