### ISSUE TITLE
Update CentOS

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/NRPTI#947]
**Additional context**
CentOS 8 is not supported anymore so the app cannot build locally unless you do a hacky fix for it.

**Definition of Done**
- [ ] Update CentOS to working version
- [ ] Remove code hack that uses vaulted version to run
- [ ] Make sure new version doesn't create errors / write tickets for errors it creates

**Comment by LolandaE** [comment]
Duplicate of Wally617
https://app.zenhub.com/workspaces/sustainment-team-621fdc6b9ad7010018d8dc2c/issues/bcgov-c/wally/617
