### ISSUE TITLE
Deploy text change to NRPTI

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#952]
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] Use existing pipeline to deploy text change to NRPTI Prod
- [ ] ensure appropriate level of documentation for NRPTI Pipeline exists
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by LolandaE** [comment]
Test ticket for testing the pipeline. There is a separate ticket that includes this work.
