### ISSUE TITLE
Setup Github Actions for NRPTI/NRCED

### ISSUE THREAD

**Issue by jakemorr** [bcgov/NRPTI#978]
**Describe the task**
The Jenkins Pipeline for NRPTI is failing and we do not have knowledge or resources to repair and make it work, instead we will focus on shifting to a Github Actions Pipeline for this product.

**Acceptance Criteria**
- [x] understanding existing Jenkins pipeline configuration
- [ ] build frontend as a docker image
- [ ] build backend as a docker image
- [ ] understand the full scope of setting up github actions as the new pipeline for NRPTI
- [ ] copy over Openshift commands to Github Actions scripts
- [ ] translate existing build container steps in Jenkins to Github Actions
- [ ] use Github Actions to push to Dev environment
- [ ] use Github Actions to push to Test environment
- [ ] use Github Actions to push to Prod environment

**Additional context**
- We may be able to get assistance from the PSU Devs, or DevOps Specialists, or Common Services Team
- the bulk of this is moving the configuration from Jenkins to Github Actions

**Comment by Keegnan** [comment]
Closing ticket and revisiting when reopening the pipeline again. Goal to make Sustainment pipelines all the same.
