### ISSUE TITLE
Restore database to previous version - NRPTI

### ISSUE THREAD

**Issue by LolandaE** [bcgov/NRPTI#993]
**Describe the task**
Restore the database to previous version as a fail-safe in case something is deployed that damages the database.

**Acceptance Criteria**
- [x] Identify how to restore this particular type of database (Mongo DB)
- [x] Attempt to restore
- [x] Document how to restore database for other developers

**Additional context**

**Comment by dmitri-korin-bcps** [comment]
### Database Backup/Restore

To mitigate the risk of data loss or corruption you can back up the application database before a new deployment and restore it if there are issues using the following process.

- Open Terminal on the database server

- Add database tools folder to the PATH environment variable if necessary

`NEWPATH=`find / -type f -name "mongorestore" -print 2>/dev/null -quit | xargs dirname`&&export PATH=$NEWPATH:$PATH`

- To back up the database run:

 `mongodump --host="localhost:27017" --username <enter your user name> --password <enter your password> --db=nrpti --archive=backup.arc --gzip`

- To restore the database from backup file run:

`mongorestore --host="localhost:27017" --username <enter your user name> --password <enter your password> --drop --archive=backup.arc --gzip --authenticationDatabase nrpti`
